# Generated by Django 5.2.4 on 2025-07-22 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('profile_type', models.CharField(choices=[('MAIN', 'Основной'), ('SPUTNIK', 'Сопровождение взрослый')], default='MAIN', max_length=50, verbose_name='Тип профиля')),
                ('middle_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('post', models.CharField(blank=True, default='', max_length=150, verbose_name='Должность')),
                ('company_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Компания')),
                ('city', models.CharField(blank=True, default='', max_length=150, verbose_name='Город')),
                ('is_email_approved', models.BooleanField(default=False, verbose_name='Email подтвержден (да/нет)')),
                ('is_phone_approved', models.BooleanField(default=False, verbose_name='Телефон подтвержден (да/нет)')),
                ('notice', models.TextField(blank=True, default='', help_text='Используется для пометок в карточке профиля', verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='ProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('post', models.CharField(blank=True, default='', max_length=150, verbose_name='Должность')),
                ('company_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Компания')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, default='', max_length=150, verbose_name='Город')),
                ('email', models.CharField(blank=True, default='', max_length=150, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'История профиля',
                'verbose_name_plural': 'Истории профиля',
            },
        ),
    ]
