# Generated by Django 5.2.4 on 2025-07-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilehistory',
            name='email',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Email'),
        ),
    ]
